# Generated by Django 3.0.3 on 2020-02-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(db_column='CategoryName', max_length=15, unique=True)),
                ('description', models.TextField(db_column='Description')),
                ('picture', models.CharField(db_column='Picture', max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplierid', models.AutoField(db_column='SupplierID', primary_key=True, serialize=False)),
                ('companyname', models.CharField(db_column='CompanyName', max_length=40)),
                ('contactname', models.CharField(db_column='ContactName', max_length=30)),
                ('contacttitle', models.CharField(db_column='ContactTitle', max_length=30)),
                ('address', models.CharField(db_column='Address', max_length=60)),
                ('city', models.CharField(db_column='City', max_length=15)),
                ('region', models.CharField(db_column='Region', max_length=15)),
                ('postalcode', models.CharField(db_column='PostalCode', max_length=10)),
                ('country', models.CharField(db_column='Country', max_length=15)),
                ('phone', models.CharField(db_column='Phone', max_length=24)),
                ('fax', models.CharField(db_column='Fax', max_length=24)),
                ('homepage', models.CharField(db_column='HomePage', max_length=255)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='ProductName', max_length=40)),
                ('quantityperunit', models.CharField(db_column='QuantityPerUnit', max_length=20)),
                ('unitprice', models.FloatField(db_column='UnitPrice')),
                ('unitsinstock', models.PositiveSmallIntegerField(db_column='UnitsInStock')),
                ('unitsonorder', models.PositiveSmallIntegerField(db_column='UnitsOnOrder')),
                ('reorderlevel', models.PositiveSmallIntegerField(db_column='ReorderLevel')),
                ('discontinued', models.CharField(db_column='Discontinued', max_length=1)),
                ('categoryid', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Categories')),
                ('supplierid', models.ForeignKey(db_column='SupplierID', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Suppliers')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
